name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Test all
      run: bash test_all.sh

    - name: Test server
      run: bash test_server.sh

    - name: Test server
      run: bash build_linux.sh

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: build/decryptorservice_x86_64.tar.gz
